import { defineConfig } from 'vite'
import { resolve, dirname, extname } from 'path';
import { readFileSync, existsSync } from 'fs';
import { fileURLToPath } from 'url';
import browserslist from 'browserslist';
import { browserslistToTargets } from 'lightningcss';

import data from './package.json' with { type: "json" };
const __dirname = dirname(fileURLToPath(import.meta.url));

// hmr.json is generated by DDEV, so fall back to the defaults for a fresh clone.
const hmrPath = resolve(__dirname, 'hmr.json');
const hmrConfig = existsSync(hmrPath)
    ? JSON.parse(readFileSync(hmrPath, 'utf-8'))
    : { host: 'localhost', port: 5173, clientPort: 5173 };

// Appended at the start of every file
const license = `/**
 *  @version        v${data.version}
 *  @description    ${data.description}
 *  @author         ${data.author.name} <${data.author.email}>
 *  @license        ${data.license} License
 */`;

const outputPath = resolve('./module/views/');

// Static files are picked up from src/static/<folder>/ and land in
// module/views/<folder>/, so the source tree mirrors the module's views folder.
const staticPath = resolve(__dirname, 'src/static');

// Emitted assets are grouped by their type instead of every asset
// (images, fonts, ...) ending up inside css/.
const assetFolders: Record<string, string[]> = {
    img: ['.avif', '.bmp', '.gif', '.ico', '.jpeg', '.jpg', '.png', '.svg', '.webp'],
    fonts: ['.eot', '.otf', '.ttf', '.woff', '.woff2']
};

const assetFolder = (file: string): string =>
    Object.entries(assetFolders)
        .find(([, extensions]) => extensions.includes(extname(file).toLowerCase()))
        ?.at(0) ?? 'css';

// This will generate multiple scripts based on the entry points (front and back)
export default defineConfig({
    // Vite serves this folder from the dev server root and copies it into
    // module/views/ on build, replacing the previous static copy targets.
    publicDir: staticPath,
    css: {
        transformer: 'lightningcss',
        lightningcss: {
            targets: browserslistToTargets(browserslist('>= 0.25%'))
        }
    },
    server: {
        // Listen on all interfaces so DDEV's router can reach the dev server.
        host: true,
        cors: true,
        // DDEV serves the project from a *.ddev.site hostname.
        allowedHosts: ['localhost', '.ddev.site'],
        hmr: {
            ...hmrConfig,
            protocol: 'wss' as const
        }
    },
    build: {
        // The entries are declared through rolldownOptions instead of build.lib,
        // because lib mode force-inlines every asset into the bundle.
        rolldownOptions: {
            input: {
                'front': resolve(__dirname, 'src/front/main.ts'),
                'back': resolve(__dirname, 'src/back/main.ts')
            },
            output: {
                entryFileNames: 'js/[name].js',
                chunkFileNames: 'js/[name].js',
                assetFileNames: (asset) => `${assetFolder(asset.names?.[0] ?? '')}/[name].[ext]`,
                banner: license
            }
        },
        // Assets below this size are inlined as data urls, bigger ones are
        // emitted into img/ or fonts/ by the assetFileNames pattern above.
        assetsInlineLimit: 4096,
        cssCodeSplit: true,
        cssMinify: 'lightningcss',
        minify: true,
        manifest: true,
        copyPublicDir: true,
        outDir: outputPath,
        emptyOutDir: false
    },
    esbuild: {
        banner: license
    },
    resolve: {
        alias: {
            '@': fileURLToPath(new URL('./src', import.meta.url))
        }
    }
});